/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as FermetureRouteImport } from './routes/fermeture'
import { Route as DepotsRouteImport } from './routes/depots'
import { Route as IndexRouteImport } from './routes/index'

const FermetureRoute = FermetureRouteImport.update({
  id: '/fermeture',
  path: '/fermeture',
  getParentRoute: () => rootRouteImport,
} as any)
const DepotsRoute = DepotsRouteImport.update({
  id: '/depots',
  path: '/depots',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/depots': typeof DepotsRoute
  '/fermeture': typeof FermetureRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/depots': typeof DepotsRoute
  '/fermeture': typeof FermetureRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/depots': typeof DepotsRoute
  '/fermeture': typeof FermetureRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/depots' | '/fermeture'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/depots' | '/fermeture'
  id: '__root__' | '/' | '/depots' | '/fermeture'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DepotsRoute: typeof DepotsRoute
  FermetureRoute: typeof FermetureRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/fermeture': {
      id: '/fermeture'
      path: '/fermeture'
      fullPath: '/fermeture'
      preLoaderRoute: typeof FermetureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/depots': {
      id: '/depots'
      path: '/depots'
      fullPath: '/depots'
      preLoaderRoute: typeof DepotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DepotsRoute: DepotsRoute,
  FermetureRoute: FermetureRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
